#!/usr/bin/env python3

import torch

print('PyTorch version: ' + torch.__version__)

print('CUDA available: ' + str(torch.cuda.is_available()))
if torch.cuda.is_available():
    print('+    CUDA version: ' + str(torch.version.cuda))

print('cuDNN available: ' + str(torch.backends.cudnn.enabled))
if torch.backends.cudnn.enabled:
    print('+    cuDNN version: ' + str(torch.backends.cudnn.version()))
